import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "../components/bootstrap-client";
import "../../public/assets/css/main.css";
import "../../public/assets/vendor/bootstrap-icons/bootstrap-icons.css";
import "../../public/admin/css/sb-admin-2.min.css";
import ReduxProvider from "@/redux/provider";
import ToastProvider from "@/components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BootstrapClient />
        <ReduxProvider>
          {children} <ToastProvider />
        </ReduxProvider>
      </body>
    </html>
  );
}
